name: Simple A133P Module Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup
      run: sudo apt-get install -y gcc-aarch64-linux-gnu git build-essential
      
    - name: Get kernel headers from device
      run: |
        # Giả lập kernel config từ A133P
        wget https://raw.githubusercontent.com/armbian/build/main/config/kernel/linux-sunxi64-current.config -O .config
        git clone https://github.com/armbian/linux.git -b sunxi-5.19 linux-armbian
        
    - name: Quick build
      run: |
        mkdir -p module
        # Tạo file source đơn giản
        cat > module/sunxi_bt.c << 'EOF'
        #include <linux/module.h>
        #include <linux/init.h>
        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("A133P");
        static int __init bt_init(void) { printk("XR829 BT Loaded\n"); return 0; }
        static void __exit bt_exit(void) { printk("XR829 BT Unloaded\n"); }
        module_init(bt_init);
        module_exit(bt_exit);
        EOF
        
        echo "obj-m += sunxi_bt.o" > module/Makefile
        make -C linux-armbian M=$PWD/module modules ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: simple-bt-module
        path: module/sunxi_bt.ko
