name: Build xradio_btlpm for ARM (4.9.191)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc kmod cpio flex bison \
          libssl-dev libncurses5-dev wget git \
          gcc-arm-linux-gnueabihf

    - name: Download kernel source (4.9.191)
      run: |
        git clone --depth=1 --branch linux-4.9.y https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git kernel
        cd kernel
        git checkout v4.9.191

    - name: Prepare kernel headers
      run: |
        cd kernel
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- defconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules_prepare

    - name: Build xradio_btlpm module
      run: |
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: xradio_btlpm-ko
        path: xradio_btlpm.ko
